language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8
install:
    - pip install -U pip setuptools
    - pip install -U coverage coveralls zope.testrunner
    - pip install -U -e .[test]
script:
    - zope-testrunner --test-path=src
notifications:
    email: false
cache: pip
